baseURL: ''
languageCode: en
title: Hugo Tailwind
theme: tailwind 
paginate: 100
defaultContentLanguage: en
markup:
    goldmark:
        renderer:
          unsafe: true
permalinks:
  pages: /:slug/
  